<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

### Exercise 1

|Term|Description|
|----|-----------|
|Subsetting|Creating a subset of data from a larger set|
|Indexing|Marking an element in stored data based on its position|
|Slicing|Removing an element subset from a larger series of elements based on the former's index within the latter|
|Masking|Replaces elements of stored data, or creates a new "Storage" of the shape shape, with Boolean values instead of the original based on some chosen condition|

### Exercise 2
```
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
```

Use masking to subset the letters that correspond to the odd numbers. I.e., get the result [A, C, E, G, I].

This is a slightly tricky problem because arrays are fussy about type. So, let me give you a recipe to solve this problem.

Subset all the first elements.
You should get array(['1', '3', '2', ..., '10', '9'])
Convert this to integers using astype(int)
You must look up how astype() works.
Use % to get the remainder for division by 2.
You should get array([1, 1, 0, ..., 0, 1]).
Use the previous result to create a mask that checks if the remainder is zero or not
You should get array([True, True, False, ..., False, True]).
Now you have identified the locations of the odd numbers.
Use the mask and extract the corresponding second elements.

In [11]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
lst = []
for pair in np_array_2d: # iterate through pairs in array
    lst.append(pair[0]) # obtain number
arr = np.array(lst).astype(int) % 2 # convert list to array then int then modulus for binary
arr.astype(bool) # convert binary to bool 

res = []
for i in range(len(arr)): # iterate through the indexes of boolean array
    if arr[i] == 1: # only acess odd numbers
        res.append(str(np_array_2d[i, 1])) # append corresponding letter to res
    
print(res)



['A', 'C', 'E', 'G', 'I']


### Exercise 3

```
[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]
```

Consider the 2D array shown above. Using your knowledge of NumPy masking, change:

1. values below 50 to -1,
2. values above 50 to +1, and
3. values equal to 50 to 0.

You should end up with:
```
[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
```

In [ ]:
import numpy as np

arr = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

n = 50
arr[arr == n] = 0 # first mask to account for 50
arr[(arr < 50) & (arr != 0)] = -1 # second mask, exlcude case of 0 signal
arr[arr > 50] = 1 # remainder cases
print(arr)





[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
